### ISSUE TITLE
Tilt support?

### ISSUE THREAD

**Issue by jkowens** [blambeau/wlang#8]
Hi I help maintain Sinatra, and I see that Tilt support was removed in this latest release. I was wondering if you had any thoughts about what we should do moving forward? Is the best option to try to get wlang support baked into Tilt? Any help is appreciated, thanks 🙏

**Comment by blambeau** [comment]
@jkowens oh right. Maybe I decided to remove Sinatra/Tilt support a bit too fast.

Quite frankly I doubt anyone uses it, and I finally never did myself, while I use Sinatra all the time...

Either I can rollback that specific change, or simply keep the 2.x branch on the long run.

WDYT would be best?

**Comment by jkowens** [comment]
@blambeau I really can't say if anyone is making use of wlang with Sinatra. We noticed because our build started failing 😄 

If you'd rather not continue supporting the Tilt template, maybe we could try opening a PR to the Tilt repo to add wlang? Would you mind taking your Tilt template and packaging it up in a PR?

**Comment by blambeau** [comment]
@jkowens I will probably restore Tilt integration here, that seems even easier actually.

**Comment by jkowens** [comment]
Ok sounds good, thank you!

**Comment by blambeau** [comment]
@jkowens we resurrected tilt & sinatra support. Can I kindly ask you to close this issue if that makes sinatra build work?

**Comment by jkowens** [comment]
Looks good, thank you! 🎉
